# Generated by Django 6.0.3 on 2026-04-02 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, verbose_name='Термин')),
                ('definition', models.CharField(max_length=500, verbose_name='Определение')),
                ('image_url', models.URLField(blank=True, verbose_name='URL иллюстрации')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='app.language')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ['term'],
            },
        ),
    ]
