# Generated by Django 6.0.3 on 2026-04-02 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_card_options_card_created_at_card_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RememberedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remembered_by', to='app.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remembered_cards', to='app.user')),
            ],
            options={
                'unique_together': {('user', 'card')},
            },
        ),
    ]
