# Generated by Django 6.0.3 on 2026-04-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rememberedcard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rememberedcard',
            options={'verbose_name': 'Запомненная карточка', 'verbose_name_plural': 'Запомненные карточки'},
        ),
    ]
