# Generated by Django 6.0.3 on 2026-04-02 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_rememberedcard_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('option1', models.CharField(max_length=200, verbose_name='Вариант 1')),
                ('option2', models.CharField(max_length=200, verbose_name='Вариант 2')),
                ('option3', models.CharField(max_length=200, verbose_name='Вариант 3')),
                ('option4', models.CharField(max_length=200, verbose_name='Вариант 4')),
                ('correct_option', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Правильный вариант')),
                ('explanation', models.TextField(blank=True, verbose_name='Пояснение')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.topic')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
